version: '3.9'

services:
  web:
    build: ./services/web
    command: flask run -h 0.0.0.0
    volumes:
      - ./services/web:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=music
volumes:
  postgres_data:

